name: Check Sorkhroud Site Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: |
          pip install requests

      - name: Test website
        run: |
          python - <<'PY'
          import requests
          import time

          url = "https://sorkhroud.ir"

          print("شروع تست سایت:", url)

          start = time.time()

          try:
              r = requests.get(
                  url,
                  timeout=15,
                  headers={
                      "User-Agent": "GitHub-Actions-HealthCheck/1.0"
                  }
              )

              ms = round((time.time() - start) * 1000, 2)

              print("Status:", r.status_code)
              print("Response:", ms, "ms")
              print("Size:", len(r.content), "bytes")

              if r.status_code < 400:
                  print("✅ سایت سالم است")
              else:
                  print("❌ خطای HTTP")

          except Exception as e:
              print("❌ Error:", e)
          PY
